In [6]:
! evo_traj tum --ref ../output/gt_traj.txt ../output/traj_viokf.txt -p -as --plot_mode=xz

--------------------------------------------------------------------------------
name:	traj_viokf
infos:	232 poses, 8.192m path length, 1078.000s duration
--------------------------------------------------------------------------------
name:	gt_traj
infos:	1083 poses, 148.337m path length, 1082.000s duration


In [1]:
!LOGGING_LEVEL=DEBUG evo_traj tum --ref ../output/gt_traj.txt ../output/traj_viokf.txt -as -v

--------------------------------------------------------------------------------
Loaded 111 stamps and poses from: ../output/traj_viokf.txt
Loaded 1083 stamps and poses from: ../output/gt_traj.txt
--------------------------------------------------------------------------------
Found 111 of max. 111 possible matching timestamps between...
	reference
and:	../output/traj_viokf.txt
..with max. time diff.: 0.01 (s) and time offset: 0.0 (s).
--------------------------------------------------------------------------------
Aligning ../output/traj_viokf.txt to reference.
Aligning using Umeyama's method... (with scale correction)
Rotation of alignment:
[[ 0.29473773  0.07824448  0.9523694 ]
 [-0.12981823 -0.98412354  0.12102927]
 [ 0.94671902 -0.1593068  -0.27990078]]
Translation of alignment:
[ 5.28929078  7.71874423 23.63646919]
Scale correction: 22.601772041553115
--------------------------------------------------------------------------------
name:	traj_viokf
infos:
	duration (s)	1072.0
	nr.

In [66]:
import numpy as np
import scipy.spatial.transform
R = np.array([[0,1,0],
                [0,0,-1],
                [-1,0,0]])
# load first line from ../output/gt_traj.txt
def load_pose(path, n=10):
    with open(path, 'r') as f:
        for i in range(n):
            line = f.readline()
        # format: timestamp tx ty tz qx qy qz qw
        data = np.array(line.split())
        t = data[1:4]
        q = data[4:]
        rot = scipy.spatial.transform.Rotation.from_quat(q).as_matrix()
    return rot, q, t

rot_gt, q_gt, t_gt = load_pose('../output/tartanair/gt_traj.txt')
rot_slam, q_slam, t_slam = load_pose('../output/tartanair/traj_viokf.txt')

print('rot_slam\n', rot_slam)

tmp_q = q_gt[[1,2,0,3]]
tmp_rot = scipy.spatial.transform.Rotation.from_quat(tmp_q).as_matrix()
tmp_rot[1:3]*=-1
print('switch\n',tmp_rot)

print('basis\n',R@rot_gt@R.T)

# R@rot_slam
# R.T@rot_gt

rot_slam
 [[-0.14581752 -0.38486032  0.91138345]
 [ 0.03506363 -0.92266172 -0.38401289]
 [ 0.98868994 -0.0240394   0.14803484]]
switch
 [[-0.16783656 -0.09288478  0.98142922]
 [ 0.00119259 -0.99556968 -0.09401912]
 [ 0.98581411 -0.01460941  0.16720376]]
basis
 [[-0.16783656  0.09288478 -0.98142922]
 [ 0.00119259  0.99556968  0.09401912]
 [ 0.98581411  0.01460941 -0.16720376]]


In [44]:
import numpy as np
import scipy.spatial.transform
R = np.array([[0,1,0],
                [0,0,1],
                [1,0,0]])
# load first line from ../output/gt_traj.txt
def load_pose(path, n=100):
    with open(path, 'r') as f:
        for i in range(n):
            line = f.readline()
        # format: timestamp tx ty tz qx qy qz qw
        print(line)
        data = np.array(line.split())
        t = data[1:4][[1,2,0]]
        q = data[4:][[1,2,0,3]]
        rot = scipy.spatial.transform.Rotation.from_quat(q).as_matrix()
    return rot, q, t

rot_gt, q_gt, t_gt = load_pose('../output/gt_traj.txt')
rot_slam, q_slam, t_slam = load_pose('../output/traj_viokf.txt')

print('rot_slam\n', rot_slam)

tmp_q = q_gt[[1,2,0,3]]
tmp_rot = scipy.spatial.transform.Rotation.from_quat(tmp_q).as_matrix()
print(tmp_rot)

print(R@rot_gt@R.T)

# R@rot_slam
# R.T@rot_gt

99 -10.991665840148926 6.599874019622803 -9.707655906677246 -0.11223653703927994 0.03780491650104523 0.6449735760688782 0.7549720406532288

420.000000 -15.915634 -27.540514 -223.936691 0.815763 0.153134 0.555781 -0.046783

rot_slam
 [[-0.94872268  0.2465455   0.19783981]
 [ 0.09389021 -0.37783795  0.92109886]
 [ 0.30184417  0.8924426   0.33531522]]
[[ 0.97194749 -0.20186252 -0.12070456]
 [-0.0876959   0.16515971 -0.98236027]
 [ 0.21823725  0.9653879   0.14282405]]
[[ 0.97194749 -0.20186252 -0.12070456]
 [-0.0876959   0.16515971 -0.98236027]
 [ 0.21823725  0.9653879   0.14282405]]
